baseURL = "http://readyZeroGo.com/"
languageCode = "en-us"
title = "Ready Zero Go"
theme = "ananke"

[params]
  body_classes = "avenir bg-near-white"
  #custom_css = ["css/custom.css","css/custom2.css"]